### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by jayvdb** [DSRCorporation/cargo-test-xunit#4]
A bit ironic.  https://github.com/DSRCorporation/cargo-test-xunit/blob/master/src/main.rs#L86 is just two dummy tests.

**Comment by vimmerru** [comment]
@jayvdb It is internal and mostly static project we use to simplify few Jenkins pipelines. So there is no big value in tests for our business, but if you want to contribute we will review and accept.

**Comment by vimmerru** [comment]
@jayvdb  I re-checked with developers. We stopped to use and support this project. If you think it is useful the best way to proceed is forking.
